In [17]:

a = 1; print(type(a))

<class 'int'>


In [1]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [28]:
### import는 하드디스크에 있는 것을 메모리로 옮기는 작업을 해준다. 그니깐 numpy라는 것을 메모리로 옮겨주는 작업을 해줌.
### numpy as np는 numpy를 단순하게 np로 이름지어주는 작업으로, 단어를 반복할때 편리하고 쉽게 적을수 있도록 해줌.
### array는 행렬과는 다르지만 비슷하다. 그래서 이미 정의된 a를 행렬 비슷하게 만들어주고 그것을 프린트 하라는 최종명령이다.
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [29]:
###   array가 행렬이 아니라는 증거이다. 만약 행렬이었다면 오류가 떠야되는 상황인데 그냥 곱해지는 상황이다 element by element로
      ### 단순히 곱한다음 프린트했다.
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [30]:
### matrix가 바로 행렬이다. 위와같은 경로로 np에서 b를 행렬으로 불러온것.
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
### arrary가 행렬이기 때문에 오류가 난 상황
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
### 2 by 3와 2by 3가 곱해져서 오류가 난거기 때문에, 2 by 3를 3 by 2 로 바꿔주는 c.T 작업을 한것이다.
c*c.T

matrix([[14, 19],
        [19, 73]])